// app/(marketing)/disclaimer/page.tsx
import type { Metadata } from 'next'
import Link from 'next/link'
import { AlertTriangle, ShieldCheck, BookOpen, Scale } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Risk Disclosure — Playbuuk',
  description:
    'Full trading risk disclosure for Playbuuk. Trading financial instruments carries substantial risk of loss. Playbuuk is an analytical discipline tool, not financial advice.',
  keywords: [
    'trading risk disclosure',
    'not financial advice',
    'forex trading risk',
    'CFD risk warning',
    'trading platform disclaimer',
  ],
  alternates: { canonical: '/disclaimer' },
  openGraph: {
    title: 'Risk Disclosure — Playbuuk',
    description:
      'Full trading risk disclosure. Trading carries substantial risk. Playbuuk is a discipline tool, not financial advice.',
    url: '/disclaimer',
  },
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="mb-10">
      <h2
        className="text-lg font-bold text-text mb-4 pb-2"
        style={{ borderBottom: '1px solid rgba(26,40,69,0.8)', letterSpacing: '-0.02em' }}
      >
        {title}
      </h2>
      <div className="space-y-3 text-sm leading-relaxed" style={{ color: '#8a9bc0' }}>
        {children}
      </div>
    </section>
  )
}

function P({ children }: { children: React.ReactNode }) { return <p>{children}</p> }
function Ul({ children }: { children: React.ReactNode }) {
  return <ul className="space-y-1.5 pl-4" style={{ listStyleType: 'disc' }}>{children}</ul>
}
function Li({ children }: { children: React.ReactNode }) { return <li>{children}</li> }
function Strong({ children }: { children: React.ReactNode }) {
  return <strong className="font-semibold text-text">{children}</strong>
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12">

      {/* Header */}
      <div className="mb-10">
        <p className="text-xs font-mono mb-3" style={{ color: 'var(--accent)' }}>Legal</p>
        <h1 className="text-3xl font-bold text-text mb-3" style={{ letterSpacing: '-0.03em' }}>
          Risk Disclosure
        </h1>
        <p className="text-sm" style={{ color: '#6b7fa3' }}>
          Last updated: <span className="font-mono">14 April 2026</span>
          {' '}· Please read this disclosure carefully before using Playbuuk.
        </p>
      </div>

      {/* Primary risk warning — prominent box */}
      <div
        className="rounded-2xl p-6 mb-10"
        style={{
          background:  'rgba(255,77,106,0.05)',
          border:      '1px solid rgba(255,77,106,0.25)',
          borderLeft:  '4px solid var(--danger)',
        }}
        role="alert"
        aria-label="High-risk warning"
      >
        <div className="flex items-start gap-3 mb-4">
          <AlertTriangle
            size={20}
            className="flex-shrink-0 mt-0.5"
            style={{ color: 'var(--danger)' }}
            aria-hidden="true"
          />
          <h2 className="text-base font-bold" style={{ color: 'var(--danger)', letterSpacing: '-0.02em' }}>
            HIGH RISK INVESTMENT WARNING
          </h2>
        </div>
        <p className="text-sm leading-relaxed" style={{ color: '#c0a0a8' }}>
          Trading in financial instruments — including but not limited to forex, CFDs,
          commodities, indices, stocks, and cryptocurrencies — <Strong>carries a substantial risk
          of loss</Strong> and may result in the loss of your entire invested capital. These
          instruments are not appropriate for all investors. You should only trade with money
          you can afford to lose entirely.
        </p>
        <p className="text-sm mt-3 leading-relaxed" style={{ color: '#c0a0a8' }}>
          <Strong>Past performance is not indicative of future results.</Strong> Any strategy,
          grade, or checklist assessment generated by Playbuuk is based on technical analysis
          of historical and current price data and does not guarantee future performance.
        </p>
        <p className="text-sm mt-3 font-semibold" style={{ color: 'var(--danger)' }}>
          If you are unsure whether trading is suitable for you, seek independent financial
          advice from a qualified and regulated financial adviser.
        </p>
      </div>

      {/* What Playbuuk is / isn't — 2-column summary */}
      <div className="grid sm:grid-cols-2 gap-4 mb-10">
        <div
          className="rounded-xl p-5"
          style={{ background: 'rgba(0,229,176,0.04)', border: '1px solid rgba(0,229,176,0.15)' }}
        >
          <div className="flex items-center gap-2 mb-3">
            <ShieldCheck size={15} style={{ color: 'var(--accent)' }} aria-hidden="true" />
            <p className="text-xs font-bold text-text">Playbuuk IS</p>
          </div>
          <ul className="space-y-2">
            {[
              'A strategy discipline and psychology management tool',
              'An analytical platform that objectively evaluates technical setups against pre-defined rules',
              'A trade journal that tracks your compliance with your own strategy',
              'A notification system that alerts you when technical conditions are met',
              'An educational resource for understanding trading psychology',
            ].map(item => (
              <li key={item} className="flex gap-2 text-xs" style={{ color: '#8a9bc0' }}>
                <span className="flex-shrink-0 font-mono font-bold" style={{ color: 'var(--accent)' }}>✓</span>
                {item}
              </li>
            ))}
          </ul>
        </div>

        <div
          className="rounded-xl p-5"
          style={{ background: 'rgba(255,77,106,0.04)', border: '1px solid rgba(255,77,106,0.15)' }}
        >
          <div className="flex items-center gap-2 mb-3">
            <AlertTriangle size={15} style={{ color: 'var(--danger)' }} aria-hidden="true" />
            <p className="text-xs font-bold text-text">Playbuuk is NOT</p>
          </div>
          <ul className="space-y-2">
            {[
              'A financial adviser or investment adviser',
              'A trading signal service or copy trading platform',
              'A broker or execution venue',
              'A guarantee of profitable trading outcomes',
              'Regulated by the FCA, SEC, or any other financial regulator',
            ].map(item => (
              <li key={item} className="flex gap-2 text-xs" style={{ color: '#8a9bc0' }}>
                <span className="flex-shrink-0 font-mono font-bold" style={{ color: 'var(--danger)' }}>✗</span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Sections */}

      <Section id="not-financial-advice" title="Not Financial Advice">
        <P>
          Nothing on the Playbuuk platform, including but not limited to setup grades, checklist
          assessments, mentor strategies, psychology insights, alert notifications, and trade journal
          analysis, constitutes financial advice, investment advice, or a recommendation to enter or
          exit any financial position.
        </P>
        <P>
          All content on the platform is provided for <Strong>educational, informational, and analytical
          purposes only</Strong>. Mentor strategies published on the platform represent the personal views and
          approaches of individual traders and should not be construed as professional investment advice.
        </P>
        <P>
          AkomzyAi Consulting, its directors, employees, contractors, and mentor partners accept no
          liability for any trading decisions made on the basis of information or assessments provided
          by the platform.
        </P>
      </Section>

      <Section id="platform-role" title="Playbuuk's Role as a Discipline Tool">
        <div className="flex items-start gap-3 rounded-xl px-4 py-4 mb-4"
          style={{ background: 'rgba(77,142,255,0.05)', border: '1px solid rgba(77,142,255,0.15)' }}
        >
          <BookOpen size={15} className="flex-shrink-0 mt-0.5" style={{ color: 'var(--blue)' }} aria-hidden="true" />
          <p className="text-xs leading-relaxed" style={{ color: '#8a9bc0' }}>
            Playbuuk&apos;s core purpose is to help traders follow their own pre-defined rules more
            consistently — not to tell them what rules to follow. The platform automates the objective
            verification of technical conditions so that trading decisions are based on data rather than
            emotion.
          </p>
        </div>
        <P>
          The <Strong>Setup Grade</Strong> (A+ through D+) is an automated technical assessment. It
          evaluates whether observable market conditions (price action, indicators, structure) meet the
          criteria defined in a mentor&apos;s strategy playbook. A high grade does not mean a trade
          will be profitable. A low grade does not mean a trade will be unprofitable.
        </P>
        <P>
          The <Strong>Psychology Gate</Strong> (minimum grade threshold for execution) is a
          self-imposed discipline mechanism. It prevents impulsive execution of setups that do not
          meet your own pre-defined standards. You may override this gate at any time. Overrides are
          logged for your own accountability — not to penalise you, but to help you identify patterns
          in your own behaviour over time.
        </P>
        <P>
          <Strong>Setup alerts</Strong> are notifications that technical conditions have been met
          according to a simulated assessment (MVP phase). They do not constitute trading signals. The
          decision to trade or not trade remains entirely yours.
        </P>
      </Section>

      <Section id="specific-risks" title="Specific Risks You Should Understand">
        <Ul>
          <Li>
            <Strong>Market risk:</Strong> Prices can move rapidly and unpredictably. Technical setups
            that appear valid can fail. No checklist or grading system can eliminate market risk.
          </Li>
          <Li>
            <Strong>Leverage risk:</Strong> Trading on margin or with leverage amplifies both gains
            and losses. A leveraged position can result in losses exceeding your initial deposit.
          </Li>
          <Li>
            <Strong>Execution risk:</Strong> Trade execution via MetaApi is subject to latency,
            slippage, broker rejection, API downtime, and connectivity failures. Playbuuk bears no
            responsibility for failed or delayed executions.
          </Li>
          <Li>
            <Strong>Strategy risk:</Strong> Mentor strategies are based on historical approaches. Past
            strategy performance is not indicative of future performance. Market conditions change.
          </Li>
          <Li>
            <Strong>Simulated data risk (MVP):</Strong> During the MVP phase, setup grades and checklist
            evaluations use simulated market data. Do not make trading decisions based solely on
            Playbuuk&apos;s grade assessment at this stage. Always independently verify market conditions.
          </Li>
          <Li>
            <Strong>Psychology risk:</Strong> While Playbuuk aims to reduce emotional trading, it cannot
            eliminate psychological biases. The grade override function means the final decision is
            always yours. Playbuuk does not absolve you of responsibility for your trading decisions.
          </Li>
          <Li>
            <Strong>Technology risk:</Strong> Reliance on any technology platform introduces the risk
            of software errors, data inaccuracies, or service interruptions. We make no warranty that
            the platform will be error-free or uninterrupted.
          </Li>
        </Ul>
      </Section>

      <Section id="regulatory" title="Regulatory Status">
        <div className="flex items-start gap-3 rounded-xl px-4 py-4"
          style={{ background: 'rgba(251,191,36,0.05)', border: '1px solid rgba(251,191,36,0.15)' }}
        >
          <Scale size={15} className="flex-shrink-0 mt-0.5" style={{ color: 'var(--gold)' }} aria-hidden="true" />
          <div className="text-xs leading-relaxed space-y-2" style={{ color: '#8a9bc0' }}>
            <p>
              AkomzyAi Consulting is <Strong>not regulated</Strong> by the Financial Conduct Authority
              (FCA) in the United Kingdom, the Securities and Exchange Commission (SEC) or Commodity
              Futures Trading Commission (CFTC) in the United States, the European Securities and
              Markets Authority (ESMA), or any other financial regulatory authority.
            </p>
            <p>
              Playbuuk does not provide regulated financial services. It is a software platform that
              provides analytical tools for self-directed traders who make their own investment decisions.
            </p>
            <p>
              <Strong>UK users:</Strong> Playbuuk does not carry on regulated activities under the
              Financial Services and Markets Act 2000. This platform does not fall under the scope
              of FCA authorisation requirements for analytical/educational software tools.
            </p>
            <p>
              <Strong>US users:</Strong> This platform does not constitute investment advice under the
              Investment Advisers Act of 1940. Signals generated by Playbuuk do not constitute
              securities recommendations.
            </p>
            <p>
              <Strong>EU users:</Strong> This platform does not provide MiFID II investment advice or
              portfolio management services.
            </p>
          </div>
        </div>
      </Section>

      <Section id="suitability" title="Suitability Warning">
        <P>
          Before trading financial instruments, you should carefully consider your investment
          objectives, level of experience, and risk appetite. You should be aware of all the risks
          associated with trading and seek advice from an independent financial adviser if you have
          any doubts.
        </P>
        <P>
          Trading may not be suitable for you if:
        </P>
        <Ul>
          <Li>You are not prepared to accept the risk of losing your entire invested capital</Li>
          <Li>You do not fully understand the mechanics and risks of the instruments you are trading</Li>
          <Li>You are trading with funds you cannot afford to lose</Li>
          <Li>You are in financial difficulty or are borrowing to fund trading activity</Li>
          <Li>You are relying on trading profits as your primary source of income without adequate capital reserves</Li>
        </Ul>
      </Section>

      <Section id="mentor-content" title="Mentor Strategy Disclaimer">
        <P>
          Trading strategies and playbooks available on Playbuuk are sourced from third-party mentors
          and public sources. They are provided for educational purposes only. AkomzyAi Consulting does
          not endorse, verify the profitability of, or take responsibility for any mentor strategy.
        </P>
        <P>
          Mentor strategies labelled <Strong>&ldquo;AI-Extracted Draft — Pending Mentor Review&rdquo;</Strong> have
          been generated automatically from public information and have not been verified by the mentor
          for accuracy. These drafts should be treated with additional caution.
        </P>
        <P>
          Mentors on the platform are independent traders sharing their personal approaches. They are
          not regulated financial advisers and their strategies should not be treated as professional
          investment advice.
        </P>
      </Section>

      {/* Footer links */}
      <div className="rounded-2xl px-5 py-4 mt-4 text-xs font-mono"
        style={{ background: 'var(--card)', border: '1px solid var(--border)', color: '#6b7fa3' }}
      >
        <p className="mb-2 font-semibold text-muted">Related documents</p>
        <div className="flex flex-wrap gap-4">
          <Link href="/terms" className="text-accent hover:text-text transition-colors underline underline-offset-2">
            Terms of Service
          </Link>
          <Link href="/privacy" className="text-accent hover:text-text transition-colors underline underline-offset-2">
            Privacy Policy
          </Link>
          <a href="mailto:legal@playbuuk.com" className="text-accent hover:text-text transition-colors underline underline-offset-2">
            legal@playbuuk.com
          </a>
        </div>
      </div>

    </div>
  )
}
